# [URLS DOS MEDIADORES]
#invitation_url=https://staging-id.cpqd.com.br/api/agent-mediator-endpoint-com?c_i=eyJAdHlwZSI6ICJodHRwczovL2RpZGNvbW0ub3JnL2Nvbm5lY3Rpb25zLzEuMC9pbnZpdGF0aW9uIiwgIkBpZCI6ICI2Mzc4YmQ4NS1jMGU0LTRlZDUtYjJiNS1iYTI1NmRhNWE5NDciLCAibGFiZWwiOiAiTWVkaWF0b3IiLCAicmVjaXBpZW50S2V5cyI6IFsiRDVMVGZNTUtrNVhIYnZVaVhiS3ZZejJlOEpwY2lVSkVlazh5TUhjWW1IaG0iXSwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL3N0YWdpbmctaWQuY3BxZC5jb20uYnIvYXBpL2FnZW50LW1lZGlhdG9yLWVuZHBvaW50LWNvbSJ9
invitation_url=https://mediador-idd13647.np.estaleiro.serpro.gov.br/http?oob=eyJAdHlwZSI6ICJodHRwczovL2RpZGNvbW0ub3JnL291dC1vZi1iYW5kLzEuMS9pbnZpdGF0aW9uIiwgIkBpZCI6ICI2NWM5MDNkNi1mMWEzLTRjMjQtODM3OS00M2I5MTZjYmYyODIiLCAibGFiZWwiOiAiTWVkaWFkb3IgQUNBLVB5IGJlc3UiLCAiaGFuZHNoYWtlX3Byb3RvY29scyI6IFsiaHR0cHM6Ly9kaWRjb21tLm9yZy9kaWRleGNoYW5nZS8xLjEiXSwgInNlcnZpY2VzIjogW3siaWQiOiAiI2lubGluZSIsICJ0eXBlIjogImRpZC1jb21tdW5pY2F0aW9uIiwgInJlY2lwaWVudEtleXMiOiBbImRpZDprZXk6ejZNa2VyQktzZTR1dHVUNmRBWnI0NDhickYzUTFSVjVqUVpVSzNtRmtHU2ZIejREI3o2TWtlckJLc2U0dXR1VDZkQVpyNDQ4YnJGM1ExUlY1alFaVUszbUZrR1NmSHo0RCJdLCAic2VydmljZUVuZHBvaW50IjogImh0dHBzOi8vbWVkaWFkb3ItaWRkMTM2NDcubnAuZXN0YWxlaXJvLnNlcnByby5nb3YuYnIvaHR0cCJ9XX0
#invitation_url=https://mediador-idd13647.np.estaleiro.serpro.gov.br/http?oob=eyJAdHlwZSI6ICJodHRwczovL2RpZGNvbW0ub3JnL291dC1vZi1iYW5kLzEuMS9pbnZpdGF0aW9uIiwgIkBpZCI6ICJiODM3NmE4Mi02OWQ1LTQ1OGUtYWZjMy0wMTI0M2E0ZTlhMmUiLCAibGFiZWwiOiAiRW1pc3NvciBBQ0EtUHkgYmVzdSIsICJoYW5kc2hha2VfcHJvdG9jb2xzIjogWyJodHRwczovL2RpZGNvbW0ub3JnL2RpZGV4Y2hhbmdlLzEuMSJdLCAic2VydmljZXMiOiBbeyJpZCI6ICIjaW5saW5lIiwgInR5cGUiOiAiZGlkLWNvbW11bmljYXRpb24iLCAicmVjaXBpZW50S2V5cyI6IFsiZGlkOmtleTp6Nk1raWlheHlKSHFTNG4za2hzYzF4em40ZnJDTWZSTGROcnBtVXBEYnE3WXpOQm8jejZNa2lpYXh5SkhxUzRuM2toc2MxeHpuNGZyQ01mUkxkTnJwbVVwRGJxN1l6TkJvIl0sICJzZXJ2aWNlRW5kcG9pbnQiOiAiaHR0cHM6Ly9tZWRpYWRvci1pZGQxMzY0Ny5ucC5lc3RhbGVpcm8uc2VycHJvLmdvdi5ici9odHRwIn1dfQ
#invitation_url=https://public.mediator.indiciotech.io?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiMDVlYzM5NDItYTEyOS00YWE3LWEzZDQtYTJmNDgwYzNjZThhIiwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL3B1YmxpYy5tZWRpYXRvci5pbmRpY2lvdGVjaC5pbyIsICJyZWNpcGllbnRLZXlzIjogWyJDc2dIQVpxSktuWlRmc3h0MmRIR3JjN3U2M3ljeFlEZ25RdEZMeFhpeDIzYiJdLCAibGFiZWwiOiAiSW5kaWNpbyBQdWJsaWMgTWVkaWF0b3IifQ==
endpoint=https://mediador-idd13647.np.estaleiro.serpro.gov.br/http

# --------- CPQD ---------
#besu_chainId=381660001
#besu_nodeAddress=https://staging-id.cpqd.com.br/api/vdr-rpc-proxy
# ------------------------
#"http://161.148.156.253:8545", "http://10.139.76.166:8000", "http://idd.serpro.gov.br/besu",

besu_chainId=1337
besu_nodeAddress=http://idd.serpro.gov.br/besu

#DID_REGISTRY_ADDRESS=0xab3B5F6401B2Ee297646E0CB3a761b3B041CbDc1
#SCHEMA_REGISTRY_ADDRESS=0x0054a3ca30a8e042431659012a89547Fb5F37B09
#CRED_DEF_REGISTRY_ADDRESS=0xC8f58773F6FE01C27813dde0F9c84BfC7400dDf0
#REVOCATION_REGISTRY_ADDRESS=0xa43c29909dB932075274Dd255EeDd426f0e3b3F5

DID_REGISTRY_ADDRESS=0x0000000000000000000000000000000000018888
SCHEMA_REGISTRY_ADDRESS=0x0000000000000000000000000000000000005555
CRED_DEF_REGISTRY_ADDRESS=0x0000000000000000000000000000000000004444
REVOCATION_REGISTRY_ADDRESS=0x0000000000000000000000000000000000002222


########## cache ##########
cache.default.ttl.days=1
creddef.ttl.map=did:ethr:serpro:0x4b5028369449d52d6e00bc3f5be5ca8c21a31a05/anoncreds/v0/CLAIM_DEF/did:ethr:serpro:0x4b5028369449d52d6e00bc3f5be5ca8c21a31a05:schema_60db0826-fe30-4ab0-b0f5-bf128a18497a:1.0/default,1;did:ethr:serpro:0x4b5028369449d52d6e00bc3f5be5ca8c21a31a05/anoncreds/v0/CLAIM_DEF/did:ethr:serpro:0x4b5028369449d52d6e00bc3f5be5ca8c21a31a05:schema_revoked_26b39cb5-6d49-4048-9333-1b527b4946aa:1.0/default,7;

# TTLs globais
cache.schema.ttl.days=30
cache.revreg.ttl.days=30
cache.tails.ttl.days=30