plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.serialization'
    id 'maven-publish'
}

android {
    //namespace 'org.hyperledger.ariesframework'
    namespace 'uniffi.indy_besu_vdr'
    compileSdk 36

    sourceSets {
        main {
            java.srcDirs = ['src/main/kotlin']
            res.srcDirs = ['src/main/res']
            assets.srcDirs = ['src/main/assets']

            // JNI
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }

    defaultConfig {
        minSdk 26
        targetSdk 36

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            shrinkResources false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
    kotlin {
        jvmToolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }
}

dependencies {
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0'
    //implementation 'org.slf4j:slf4j-api:1.7.32'
    //implementation 'ch.qos.logback:logback-classic:1.2.6'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.7.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-datetime:0.4.0'
    implementation 'com.squareup.okhttp3:okhttp:4.10.0'
    implementation 'org.didcommx:peerdid:0.5.0'
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'net.java.dev.jna:jna:5.12.0@aar'
}

def getExtraString(name) {
    try {
        return ext[name]
    } catch (ignored) {
        return ""
    }
}

afterEvaluate {
    publishing {
        repositories {

            // opcional
            mavenLocal()
        }

        publications {
            snapshot(MavenPublication) {
                from components.release
                groupId = getExtraString("GROUP")
                version = getExtraString("VERSION_NAME")
                artifactId = "ledger-besu-wrapper"
            }
        }
    }
}